import { useState } from "react";

export default function LandingPage() {
  const [uniqueId, setUniqueId] = useState("482391728451");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const generateDummyId = () => {
    const id = Math.floor(
      100000000000 + Math.random() * 900000000000,
    ).toString();

    setUniqueId(id);
  };

  const handleCreateAccount = () => {
    alert("Backend not implemented yet.");
  };

  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      {/* Hero */}
      <section className="mx-auto max-w-6xl px-6 py-10">
        <h1 className="text-5xl font-bold">
          Browser-first Peer-to-Peer Communication
        </h1>
        <p className="mx-auto mt-1 max-w-3xl text-lg leading-8 text-slate-300">
          A communication platform that minimizes server dependency while
          keeping the user in control. No email address. No phone number. Just a
          randomly generated unique identifier and direct peer-to-peer
          communication whenever possible.
        </p>
      </section>

      {/* Philosophy */}
      <section className="mx-auto grid max-w-6xl gap-12 px-3 py-2 md:grid-cols-2">
        <div>
          <h2 className="mb-2 text-3xl font-semibold">What We Care About</h2>
          <ul className="flex flex-row gap-3 flex-wrap justify-evenly space-y-1 text-slate-300">
            <li>✔ Browser-first experience</li>
            <li>✔ Peer-to-peer communication</li>
            <li>✔ Minimal personal information</li>
            <li>✔ Simple user experience</li>
            <li>✔ Open architecture</li>
            <li>✔ Fast interface</li>
            <li>✔ Modern web standards</li>
          </ul>
        </div>

        <div>
          <h2 className="mb-2 text-3xl font-semibold">
            What We Don't Care About
          </h2>

          <ul className="flex flex-row gap-3 flex-wrap justify-evenly space-y-1 text-slate-300">
            <li>✖ Phone number verification</li>
            <li>✖ Email verification</li>
            <li>✖ Advertising</li>
            <li>✖ User profiling</li>
            <li>✖ Recommendation algorithms</li>
            <li>✖ Social media features</li>
            <li>✖ Collecting unnecessary personal information</li>
          </ul>
        </div>
      </section>

      {/* Registration */}
      <section className="mx-auto max-w-3xl px-6 py-20">
        <div className="rounded-xl border border-slate-800 bg-slate-900 p-8 shadow-lg">
          <h2 className="text-3xl font-semibold">Create Your Account</h2>

          <p className="mt-3 text-slate-400">
            This section is currently a frontend demonstration. The unique
            identifier will eventually be generated by the backend and stored
            securely along with your password.
          </p>

          <div className="mt-10 space-y-6">
            <div>
              <label className="mb-2 block text-sm font-medium">
                Unique ID
              </label>

              <div className="flex gap-3">
                <input
                  value={uniqueId}
                  readOnly
                  className="flex-1 rounded-lg border border-slate-700 bg-slate-950 px-4 py-3 font-mono"
                />

                <button
                  onClick={generateDummyId}
                  className="rounded-lg bg-blue-600 px-5 py-3 font-medium transition hover:bg-blue-700"
                >
                  Generate
                </button>
              </div>
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium">Name</label>

              <input
                type="text"
                placeholder="Enter your name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                className="w-full rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"
              />
            </div>
            <div>
              <label className="mb-2 block text-sm font-medium">Password</label>

              <input
                type="password"
                placeholder="Enter password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"
              />
            </div>

            <div>
              <label className="mb-2 block text-sm font-medium">
                Confirm Password
              </label>

              <input
                type="password"
                placeholder="Confirm password"
                value={confirmPassword}
                onChange={(e) => setConfirmPassword(e.target.value)}
                className="w-full rounded-lg border border-slate-700 bg-slate-950 px-4 py-3"
              />
            </div>

            <button
              onClick={handleCreateAccount}
              className="w-full rounded-lg bg-green-600 py-3 text-lg font-semibold transition hover:bg-green-700"
            >
              Create Account
            </button>

            <div className="rounded-lg bg-slate-950 p-4 text-sm text-slate-400">
              <p>
                Your unique ID is the only identifier required to access your
                account.
              </p>

              <p className="mt-2">
                Keep it safe. It cannot be recovered if lost.
              </p>

              <p className="mt-2">
                No email address or phone number is required.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="mx-auto max-w-4xl px-6 py-16">
        <h2 className="mb-8 text-3xl font-semibold">
          Frequently Asked Questions
        </h2>

        <div className="space-y-6">
          <div>
            <h3 className="font-semibold">Why don't you ask for my email?</h3>

            <p className="mt-2 text-slate-400">
              Because the intended authentication model does not require one.
            </p>
          </div>

          <div>
            <h3 className="font-semibold">Can I create multiple accounts?</h3>

            <p className="mt-2 text-slate-400">
              Yes. Every account receives its own unique identifier.
            </p>
          </div>

          <div>
            <h3 className="font-semibold">Is this production ready?</h3>

            <p className="mt-2 text-slate-400">
              No. The project is currently under active development.
            </p>
          </div>
        </div>
      </section>

      {/* Project Status */}
      <section className="mx-auto max-w-4xl px-6 py-16">
        <h2 className="mb-8 text-3xl font-semibold">Project Status</h2>

        <div className="grid gap-4 sm:grid-cols-2">
          <div>✅ React + Vite</div>
          <div>✅ TypeScript</div>
          <div>✅ Tailwind CSS</div>
          <div>✅ Cloudflare Pages</div>
          <div>⏳ Backend</div>
          <div>⏳ Signaling Server</div>
          <div>⏳ STUN Server</div>
          <div>⏳ Peer-to-Peer Messaging</div>
          <div>⏳ File Transfer</div>
          <div>⏳ Voice & Video Calls</div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-slate-800 py-10 text-center text-sm text-slate-500">
        <p>P2P Web App</p>
        <p className="mt-2">Version 0.1.0</p>
        <p className="mt-2">MIT License</p>
        <p className="mt-4">
          Built as an experiment in browser-native peer-to-peer communication.
        </p>
      </footer>
    </main>
  );
}
